"""Add revenue tracking

Revision ID: 4bb117c86078
Revises: bddeea9e45d6
Create Date: 2025-03-27 06:23:56.748942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb117c86078'
down_revision = 'bddeea9e45d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenues',
    sa.Column('revID', sa.String(length=20), nullable=False),
    sa.Column('revDate', sa.Date(), nullable=False),
    sa.Column('revTime', sa.String(length=5), nullable=False),
    sa.Column('revDescription', sa.String(length=50), nullable=False),
    sa.Column('revAmount', sa.Float(), nullable=False),
    sa.Column('revType', sa.String(length=20), nullable=False),
    sa.Column('userID', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('revID')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isExpense', sa.Boolean(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthlyIncome', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('monthlyIncome')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('isExpense')

    op.drop_table('revenues')
    # ### end Alembic commands ###
