"""Add Bank Interest to revenue types

Revision ID: fdda610a59f5
Revises: 4bb117c86078
Create Date: 2025-03-27 10:59:31.152412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdda610a59f5'
down_revision = '4bb117c86078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revenues', schema=None) as batch_op:
        batch_op.alter_column('revType',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('Salary', 'Freelance', 'Investments', 'Rent', 'Other', 'Bank Interest'),
               existing_nullable=False)
        batch_op.drop_column('revTime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revenues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revTime', mysql.VARCHAR(length=5), nullable=False))
        batch_op.alter_column('revType',
               existing_type=sa.Enum('Salary', 'Freelance', 'Investments', 'Rent', 'Other', 'Bank Interest'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
